#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright byteyang. All Rights Reserved.
"""从 Resources/legacy_capability_names.json 生成 C++ TMap 片段。

用法：
  py scripts/gen_legacy_capability_names.py          # 写出 generated.inl
  py scripts/gen_legacy_capability_names.py --check  # 与已提交文件比对，不一致则 exit 1
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_PLUGIN = Path(__file__).resolve().parent.parent
_JSON = _PLUGIN / "Resources" / "legacy_capability_names.json"
_INL = _PLUGIN / "Source" / "NexusLink" / "Private" / "Utils" / "NexusCapabilityLegacyNames.generated.inl"


def render_inl(mapping: dict[str, str]) -> str:
    lines = [
        "// Copyright byteyang. All Rights Reserved.",
        "// GENERATED by scripts/gen_legacy_capability_names.py — do not edit.",
        "",
    ]
    for k, v in mapping.items():
        lines.append(f'\t\t\t{{ TEXT("{k}"), TEXT("{v}") }},')
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mapping = json.loads(_JSON.read_text(encoding="utf-8"))
    if not isinstance(mapping, dict) or not mapping:
        print("legacy_capability_names.json must be a non-empty object", file=sys.stderr)
        return 1
    text = render_inl(mapping)
    if args.check:
        if not _INL.is_file():
            print(f"missing {_INL}", file=sys.stderr)
            return 1
        existing = _INL.read_text(encoding="utf-8")
        if existing.replace("\r\n", "\n") != text.replace("\r\n", "\n"):
            print("NexusCapabilityLegacyNames.generated.inl is stale; re-run gen_legacy_capability_names.py", file=sys.stderr)
            return 1
        return 0
    _INL.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {_INL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
